name: Test BackApp

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      build_architecture:
        required: false
        type: string
        default: 'amd64'
  push:
    branches:
      - '**'

permissions:
  contents: read
  checks: write

jobs:
  build:
    uses: ./.github/workflows/binary.build.yml
    with:
      build_architecture: ${{ inputs.build_architecture || 'amd64' }}
    secrets: inherit
  test:
    name: Run Playwright Tests
    needs: build
    if: ${{ needs.build.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Linux amd64 binary
        uses: actions/download-artifact@v4
        with:
          name: backapp-server-linux-amd64
          path: build

      - name: Rename binary for testing
        run: mv build/backapp-server-linux-amd64 build/backapp-server

      - name: Set executable permissions
        run: chmod +x build/backapp-server

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install frontend dependencies
        working-directory: web
        run: npm ci

      - name: Cache Playwright Binaries
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('./web/package-lock.json') }}
      - name: Install Playwright Browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        working-directory: ./web
        run: npx playwright install --with-deps

      - name: Run Playwright tests with JUnit output
        working-directory: web
        run: |
          npm run test-ci

      - name: Stop backend
        if: always()
        run: |
          kill $(cat server/backapp.pid) || true

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: web/test-results/results.xml
          check_name: E2E Tests
          detailed_summary: true
      - name: Upload Test Report html
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: E2E html report
          path: web/test-results/html
          retention-days: 1
